# {{ ansible_managed }}
FROM uibmz/opsi-server:{{ ludus_opsi_image_tag }}
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      libnss-sss libpam-sss \
 && sed -ri '/^passwd:/{/ sss/!s/$/ sss/}; /^group:/{/ sss/!s/$/ sss/}; /^shadow:/{/ sss/!s/$/ sss/}' /etc/nsswitch.conf \
 && pam-auth-update --enable sss \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
